name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - run: npm ci --legacy-peer-deps
      - run: npm run build:web
      - run: npx cap sync android
      - run: ./gradlew assemble --no-daemon
        working-directory: ./android

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci --legacy-peer-deps
      - run: npm run build:web
      - run: npm run lint
