name: Create release

on:
  push:
    branches: [main]

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  web-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - uses: actions/configure-pages@v4
      - run: npm ci --legacy-peer-deps
      - run: npm run build:web
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/

  web-deploy:
    needs: web-build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - run: npm ci --legacy-peer-deps
      - run: npm run build:web
      - run: npx cap sync android
      - run: ./gradlew assemble --no-daemon
        working-directory: ./android
      - uses: actions/upload-artifact@v4
        with:
          name: luna.apk
          path: ./android/app/build/outputs/apk/release/app-release-unsigned.apk
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: luna-debug.apk
          path: ./android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
